<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Errors;

use Pago\Models\Components;
use Pago\Utils;
class HTTPValidationError
{
    /**
     * $detail
     *
     * @var ?array<\Pago\Models\Components\ValidationError> $detail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('detail')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Pago\Models\Components\ValidationError>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $detail = null;

    /**
     * @param  ?array<\Pago\Models\Components\ValidationError>  $detail
     * @phpstan-pure
     */
    public function __construct(?array $detail = null)
    {
        $this->detail = $detail;
    }

    public function toException(): HTTPValidationErrorThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new HTTPValidationErrorThrowable($message, (int) $code, $this);
    }
}