workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Pago-OAS:
        inputs:
            - location: https://api.pago.sh/openapi.json
        overlays:
            - location: https://raw.githubusercontent.com/pago-sh/pago/main/sdk/overlays/security.yml
            - location: https://raw.githubusercontent.com/pago-sh/pago/main/sdk/overlays/type_parameter.yml
            - location: https://raw.githubusercontent.com/pago-sh/pago/main/sdk/overlays/read_only.yml
            - location: https://raw.githubusercontent.com/pago-sh/pago/main/sdk/overlays/event_discriminator.yml
            - location: https://raw.githubusercontent.com/pago-sh/pago/main/sdk/overlays/timezone_enum.yml
            - location: https://raw.githubusercontent.com/pago-sh/pago/main/sdk/overlays/event_metadata.yml
        registry:
            location: registry.speakeasyapi.dev/pago/pago/pago-oas
targets:
    pago:
        target: php
        source: Pago-OAS
        publish:
            packagist:
                username: pago
                token: $packagist_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/pago/pago/pago-api-php-code-samples
            labelOverride:
                fixedValue: PHP (SDK)
            blocking: false
