<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class BenefitsUpdateRequest
{
    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Pago\Models\Components\BenefitCustomUpdate|\Pago\Models\Components\BenefitDiscordUpdate|\Pago\Models\Components\BenefitGitHubRepositoryUpdate|\Pago\Models\Components\BenefitDownloadablesUpdate|\Pago\Models\Components\BenefitLicenseKeysUpdate|\Pago\Models\Components\BenefitMeterCreditUpdate|\Pago\Models\Components\BenefitFeatureFlagUpdate $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\BenefitCustomUpdate|Components\BenefitDiscordUpdate|Components\BenefitGitHubRepositoryUpdate|Components\BenefitDownloadablesUpdate|Components\BenefitLicenseKeysUpdate|Components\BenefitMeterCreditUpdate|Components\BenefitFeatureFlagUpdate $requestBody;

    /**
     * @param  string  $id
     * @param  \Pago\Models\Components\BenefitCustomUpdate|\Pago\Models\Components\BenefitDiscordUpdate|\Pago\Models\Components\BenefitGitHubRepositoryUpdate|\Pago\Models\Components\BenefitDownloadablesUpdate|\Pago\Models\Components\BenefitLicenseKeysUpdate|\Pago\Models\Components\BenefitMeterCreditUpdate|\Pago\Models\Components\BenefitFeatureFlagUpdate  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $id, Components\BenefitCustomUpdate|Components\BenefitDiscordUpdate|Components\BenefitGitHubRepositoryUpdate|Components\BenefitDownloadablesUpdate|Components\BenefitLicenseKeysUpdate|Components\BenefitMeterCreditUpdate|Components\BenefitFeatureFlagUpdate $requestBody)
    {
        $this->id = $id;
        $this->requestBody = $requestBody;
    }
}