<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class CheckoutsClientUpdateRequest
{
    /**
     * The checkout session client secret.
     *
     * @var string $clientSecret
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=client_secret')]
    public string $clientSecret;

    /**
     *
     * @var \Pago\Models\Components\CheckoutUpdatePublic $checkoutUpdatePublic
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CheckoutUpdatePublic $checkoutUpdatePublic;

    /**
     * @param  string  $clientSecret
     * @param  \Pago\Models\Components\CheckoutUpdatePublic  $checkoutUpdatePublic
     * @phpstan-pure
     */
    public function __construct(string $clientSecret, Components\CheckoutUpdatePublic $checkoutUpdatePublic)
    {
        $this->clientSecret = $clientSecret;
        $this->checkoutUpdatePublic = $checkoutUpdatePublic;
    }
}