<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class CheckoutsClientConfirmRequest
{
    /**
     * The checkout session client secret.
     *
     * @var string $clientSecret
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=client_secret')]
    public string $clientSecret;

    /**
     *
     * @var \Pago\Models\Components\CheckoutConfirmStripe $checkoutConfirmStripe
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CheckoutConfirmStripe $checkoutConfirmStripe;

    /**
     * @param  string  $clientSecret
     * @param  \Pago\Models\Components\CheckoutConfirmStripe  $checkoutConfirmStripe
     * @phpstan-pure
     */
    public function __construct(string $clientSecret, Components\CheckoutConfirmStripe $checkoutConfirmStripe)
    {
        $this->clientSecret = $clientSecret;
        $this->checkoutConfirmStripe = $checkoutConfirmStripe;
    }
}