<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class CustomerPortalSubscriptionsUpdateRequest
{
    /**
     * The subscription ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Pago\Models\Components\CustomerSubscriptionUpdateProduct|\Pago\Models\Components\CustomerSubscriptionUpdateSeats|\Pago\Models\Components\CustomerSubscriptionCancel $customerSubscriptionUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CustomerSubscriptionUpdateProduct|Components\CustomerSubscriptionUpdateSeats|Components\CustomerSubscriptionCancel $customerSubscriptionUpdate;

    /**
     * @param  string  $id
     * @param  \Pago\Models\Components\CustomerSubscriptionUpdateProduct|\Pago\Models\Components\CustomerSubscriptionUpdateSeats|\Pago\Models\Components\CustomerSubscriptionCancel  $customerSubscriptionUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\CustomerSubscriptionUpdateProduct|Components\CustomerSubscriptionUpdateSeats|Components\CustomerSubscriptionCancel $customerSubscriptionUpdate)
    {
        $this->id = $id;
        $this->customerSubscriptionUpdate = $customerSubscriptionUpdate;
    }
}