<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class CustomersUpdateExternalRequest
{
    /**
     * The customer external ID.
     *
     * @var string $externalId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=external_id')]
    public string $externalId;

    /**
     *
     * @var \Pago\Models\Components\CustomerUpdateExternalID $customerUpdateExternalID
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CustomerUpdateExternalID $customerUpdateExternalID;

    /**
     * @param  string  $externalId
     * @param  \Pago\Models\Components\CustomerUpdateExternalID  $customerUpdateExternalID
     * @phpstan-pure
     */
    public function __construct(string $externalId, Components\CustomerUpdateExternalID $customerUpdateExternalID)
    {
        $this->externalId = $externalId;
        $this->customerUpdateExternalID = $customerUpdateExternalID;
    }
}