<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
class CustomerPortalBenefitGrantsUpdateResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var \Psr\Http\Message\ResponseInterface $rawResponse
     */
    public \Psr\Http\Message\ResponseInterface $rawResponse;

    /**
     * Benefit grant updated.
     *
     * @var \Pago\Models\Components\CustomerBenefitGrantDiscord|\Pago\Models\Components\CustomerBenefitGrantGitHubRepository|\Pago\Models\Components\CustomerBenefitGrantDownloadables|\Pago\Models\Components\CustomerBenefitGrantLicenseKeys|\Pago\Models\Components\CustomerBenefitGrantCustom|\Pago\Models\Components\CustomerBenefitGrantMeterCredit|\Pago\Models\Components\CustomerBenefitGrantFeatureFlag|null $customerBenefitGrant
     */
    public Components\CustomerBenefitGrantDiscord|Components\CustomerBenefitGrantGitHubRepository|Components\CustomerBenefitGrantDownloadables|Components\CustomerBenefitGrantLicenseKeys|Components\CustomerBenefitGrantCustom|Components\CustomerBenefitGrantMeterCredit|Components\CustomerBenefitGrantFeatureFlag|null $customerBenefitGrant = null;

    /**
     * @param  string  $contentType
     * @param  int  $statusCode
     * @param  \Psr\Http\Message\ResponseInterface  $rawResponse
     * @param  \Pago\Models\Components\CustomerBenefitGrantDiscord|\Pago\Models\Components\CustomerBenefitGrantGitHubRepository|\Pago\Models\Components\CustomerBenefitGrantDownloadables|\Pago\Models\Components\CustomerBenefitGrantLicenseKeys|\Pago\Models\Components\CustomerBenefitGrantCustom|\Pago\Models\Components\CustomerBenefitGrantMeterCredit|\Pago\Models\Components\CustomerBenefitGrantFeatureFlag|null  $customerBenefitGrant
     * @phpstan-pure
     */
    public function __construct(string $contentType, int $statusCode, \Psr\Http\Message\ResponseInterface $rawResponse, Components\CustomerBenefitGrantDiscord|Components\CustomerBenefitGrantGitHubRepository|Components\CustomerBenefitGrantDownloadables|Components\CustomerBenefitGrantLicenseKeys|Components\CustomerBenefitGrantCustom|Components\CustomerBenefitGrantMeterCredit|Components\CustomerBenefitGrantFeatureFlag|null $customerBenefitGrant = null)
    {
        $this->contentType = $contentType;
        $this->statusCode = $statusCode;
        $this->rawResponse = $rawResponse;
        $this->customerBenefitGrant = $customerBenefitGrant;
    }
}