<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class CustomerPortalOrdersUpdateRequest
{
    /**
     * The order ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Pago\Models\Components\CustomerOrderUpdate $customerOrderUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CustomerOrderUpdate $customerOrderUpdate;

    /**
     * @param  string  $id
     * @param  \Pago\Models\Components\CustomerOrderUpdate  $customerOrderUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\CustomerOrderUpdate $customerOrderUpdate)
    {
        $this->id = $id;
        $this->customerOrderUpdate = $customerOrderUpdate;
    }
}