<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class CustomerPortalBenefitGrantsUpdateRequest
{
    /**
     * The benefit grant ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Pago\Models\Components\CustomerBenefitGrantDiscordUpdate|\Pago\Models\Components\CustomerBenefitGrantGitHubRepositoryUpdate|\Pago\Models\Components\CustomerBenefitGrantDownloadablesUpdate|\Pago\Models\Components\CustomerBenefitGrantLicenseKeysUpdate|\Pago\Models\Components\CustomerBenefitGrantCustomUpdate|\Pago\Models\Components\CustomerBenefitGrantMeterCreditUpdate|\Pago\Models\Components\CustomerBenefitGrantFeatureFlagUpdate $customerBenefitGrantUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\CustomerBenefitGrantDiscordUpdate|Components\CustomerBenefitGrantGitHubRepositoryUpdate|Components\CustomerBenefitGrantDownloadablesUpdate|Components\CustomerBenefitGrantLicenseKeysUpdate|Components\CustomerBenefitGrantCustomUpdate|Components\CustomerBenefitGrantMeterCreditUpdate|Components\CustomerBenefitGrantFeatureFlagUpdate $customerBenefitGrantUpdate;

    /**
     * @param  string  $id
     * @param  \Pago\Models\Components\CustomerBenefitGrantDiscordUpdate|\Pago\Models\Components\CustomerBenefitGrantGitHubRepositoryUpdate|\Pago\Models\Components\CustomerBenefitGrantDownloadablesUpdate|\Pago\Models\Components\CustomerBenefitGrantLicenseKeysUpdate|\Pago\Models\Components\CustomerBenefitGrantCustomUpdate|\Pago\Models\Components\CustomerBenefitGrantMeterCreditUpdate|\Pago\Models\Components\CustomerBenefitGrantFeatureFlagUpdate  $customerBenefitGrantUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\CustomerBenefitGrantDiscordUpdate|Components\CustomerBenefitGrantGitHubRepositoryUpdate|Components\CustomerBenefitGrantDownloadablesUpdate|Components\CustomerBenefitGrantLicenseKeysUpdate|Components\CustomerBenefitGrantCustomUpdate|Components\CustomerBenefitGrantMeterCreditUpdate|Components\CustomerBenefitGrantFeatureFlagUpdate $customerBenefitGrantUpdate)
    {
        $this->id = $id;
        $this->customerBenefitGrantUpdate = $customerBenefitGrantUpdate;
    }
}