<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Utils\SpeakeasyMetadata;
class CustomerSeatsGetClaimInfoRequest
{
    /**
     *
     * @var string $invitationToken
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=invitation_token')]
    public string $invitationToken;

    /**
     * @param  string  $invitationToken
     * @phpstan-pure
     */
    public function __construct(string $invitationToken)
    {
        $this->invitationToken = $invitationToken;
    }
}