<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Utils\SpeakeasyMetadata;
class CustomerSeatsResendInvitationRequest
{
    /**
     *
     * @var string $seatId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=seat_id')]
    public string $seatId;

    /**
     * @param  string  $seatId
     * @phpstan-pure
     */
    public function __construct(string $seatId)
    {
        $this->seatId = $seatId;
    }
}