<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class DiscountsUpdateRequest
{
    /**
     * The discount ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Pago\Models\Components\DiscountUpdate $discountUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\DiscountUpdate $discountUpdate;

    /**
     * @param  string  $id
     * @param  \Pago\Models\Components\DiscountUpdate  $discountUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\DiscountUpdate $discountUpdate)
    {
        $this->id = $id;
        $this->discountUpdate = $discountUpdate;
    }
}