<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
class EventsGetResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var \Psr\Http\Message\ResponseInterface $rawResponse
     */
    public \Psr\Http\Message\ResponseInterface $rawResponse;

    /**
     * Successful Response
     *
     * @var \Pago\Models\Components\MeterCreditEvent|\Pago\Models\Components\MeterResetEvent|\Pago\Models\Components\BenefitGrantedEvent|\Pago\Models\Components\BenefitCycledEvent|\Pago\Models\Components\BenefitUpdatedEvent|\Pago\Models\Components\BenefitRevokedEvent|\Pago\Models\Components\SubscriptionCreatedEvent|\Pago\Models\Components\SubscriptionUpdatedEvent|\Pago\Models\Components\SubscriptionCycledEvent|\Pago\Models\Components\SubscriptionCanceledEvent|\Pago\Models\Components\SubscriptionRevokedEvent|\Pago\Models\Components\SubscriptionUncanceledEvent|\Pago\Models\Components\SubscriptionProductUpdatedEvent|\Pago\Models\Components\SubscriptionSeatsUpdatedEvent|\Pago\Models\Components\SubscriptionBillingPeriodUpdatedEvent|\Pago\Models\Components\OrderPaidEvent|\Pago\Models\Components\OrderRefundedEvent|\Pago\Models\Components\OrderVoidedEvent|\Pago\Models\Components\CheckoutCreatedEvent|\Pago\Models\Components\CustomerCreatedEvent|\Pago\Models\Components\CustomerUpdatedEvent|\Pago\Models\Components\CustomerDeletedEvent|\Pago\Models\Components\BalanceOrderEvent|\Pago\Models\Components\BalanceCreditOrderEvent|\Pago\Models\Components\BalanceRefundEvent|\Pago\Models\Components\BalanceRefundReversalEvent|\Pago\Models\Components\BalanceDisputeEvent|\Pago\Models\Components\BalanceDisputeReversalEvent|\Pago\Models\Components\UserEvent|null $event
     */
    public Components\MeterCreditEvent|Components\MeterResetEvent|Components\BenefitGrantedEvent|Components\BenefitCycledEvent|Components\BenefitUpdatedEvent|Components\BenefitRevokedEvent|Components\SubscriptionCreatedEvent|Components\SubscriptionUpdatedEvent|Components\SubscriptionCycledEvent|Components\SubscriptionCanceledEvent|Components\SubscriptionRevokedEvent|Components\SubscriptionUncanceledEvent|Components\SubscriptionProductUpdatedEvent|Components\SubscriptionSeatsUpdatedEvent|Components\SubscriptionBillingPeriodUpdatedEvent|Components\OrderPaidEvent|Components\OrderRefundedEvent|Components\OrderVoidedEvent|Components\CheckoutCreatedEvent|Components\CustomerCreatedEvent|Components\CustomerUpdatedEvent|Components\CustomerDeletedEvent|Components\BalanceOrderEvent|Components\BalanceCreditOrderEvent|Components\BalanceRefundEvent|Components\BalanceRefundReversalEvent|Components\BalanceDisputeEvent|Components\BalanceDisputeReversalEvent|Components\UserEvent|null $event = null;

    /**
     * @param  string  $contentType
     * @param  int  $statusCode
     * @param  \Psr\Http\Message\ResponseInterface  $rawResponse
     * @param  \Pago\Models\Components\MeterCreditEvent|\Pago\Models\Components\MeterResetEvent|\Pago\Models\Components\BenefitGrantedEvent|\Pago\Models\Components\BenefitCycledEvent|\Pago\Models\Components\BenefitUpdatedEvent|\Pago\Models\Components\BenefitRevokedEvent|\Pago\Models\Components\SubscriptionCreatedEvent|\Pago\Models\Components\SubscriptionUpdatedEvent|\Pago\Models\Components\SubscriptionCycledEvent|\Pago\Models\Components\SubscriptionCanceledEvent|\Pago\Models\Components\SubscriptionRevokedEvent|\Pago\Models\Components\SubscriptionUncanceledEvent|\Pago\Models\Components\SubscriptionProductUpdatedEvent|\Pago\Models\Components\SubscriptionSeatsUpdatedEvent|\Pago\Models\Components\SubscriptionBillingPeriodUpdatedEvent|\Pago\Models\Components\OrderPaidEvent|\Pago\Models\Components\OrderRefundedEvent|\Pago\Models\Components\OrderVoidedEvent|\Pago\Models\Components\CheckoutCreatedEvent|\Pago\Models\Components\CustomerCreatedEvent|\Pago\Models\Components\CustomerUpdatedEvent|\Pago\Models\Components\CustomerDeletedEvent|\Pago\Models\Components\BalanceOrderEvent|\Pago\Models\Components\BalanceCreditOrderEvent|\Pago\Models\Components\BalanceRefundEvent|\Pago\Models\Components\BalanceRefundReversalEvent|\Pago\Models\Components\BalanceDisputeEvent|\Pago\Models\Components\BalanceDisputeReversalEvent|\Pago\Models\Components\UserEvent|null  $event
     * @phpstan-pure
     */
    public function __construct(string $contentType, int $statusCode, \Psr\Http\Message\ResponseInterface $rawResponse, Components\MeterCreditEvent|Components\MeterResetEvent|Components\BenefitGrantedEvent|Components\BenefitCycledEvent|Components\BenefitUpdatedEvent|Components\BenefitRevokedEvent|Components\SubscriptionCreatedEvent|Components\SubscriptionUpdatedEvent|Components\SubscriptionCycledEvent|Components\SubscriptionCanceledEvent|Components\SubscriptionRevokedEvent|Components\SubscriptionUncanceledEvent|Components\SubscriptionProductUpdatedEvent|Components\SubscriptionSeatsUpdatedEvent|Components\SubscriptionBillingPeriodUpdatedEvent|Components\OrderPaidEvent|Components\OrderRefundedEvent|Components\OrderVoidedEvent|Components\CheckoutCreatedEvent|Components\CustomerCreatedEvent|Components\CustomerUpdatedEvent|Components\CustomerDeletedEvent|Components\BalanceOrderEvent|Components\BalanceCreditOrderEvent|Components\BalanceRefundEvent|Components\BalanceRefundReversalEvent|Components\BalanceDisputeEvent|Components\BalanceDisputeReversalEvent|Components\UserEvent|null $event = null)
    {
        $this->contentType = $contentType;
        $this->statusCode = $statusCode;
        $this->rawResponse = $rawResponse;
        $this->event = $event;
    }
}