<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class EventTypesUpdateRequest
{
    /**
     * The event type ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Pago\Models\Components\EventTypeUpdate $eventTypeUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\EventTypeUpdate $eventTypeUpdate;

    /**
     * @param  string  $id
     * @param  \Pago\Models\Components\EventTypeUpdate  $eventTypeUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\EventTypeUpdate $eventTypeUpdate)
    {
        $this->id = $id;
        $this->eventTypeUpdate = $eventTypeUpdate;
    }
}