<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class LicenseKeysUpdateRequest
{
    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Pago\Models\Components\LicenseKeyUpdate $licenseKeyUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\LicenseKeyUpdate $licenseKeyUpdate;

    /**
     * @param  string  $id
     * @param  \Pago\Models\Components\LicenseKeyUpdate  $licenseKeyUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\LicenseKeyUpdate $licenseKeyUpdate)
    {
        $this->id = $id;
        $this->licenseKeyUpdate = $licenseKeyUpdate;
    }
}