<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class MetricsUpdateDashboardRequest
{
    /**
     * The metric dashboard ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Pago\Models\Components\MetricDashboardUpdate $metricDashboardUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\MetricDashboardUpdate $metricDashboardUpdate;

    /**
     * @param  string  $id
     * @param  \Pago\Models\Components\MetricDashboardUpdate  $metricDashboardUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\MetricDashboardUpdate $metricDashboardUpdate)
    {
        $this->id = $id;
        $this->metricDashboardUpdate = $metricDashboardUpdate;
    }
}