<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
class Oauth2AuthorizeResponse
{
    /**
     * HTTP response content type for this operation
     *
     * @var string $contentType
     */
    public string $contentType;

    /**
     * HTTP response status code for this operation
     *
     * @var int $statusCode
     */
    public int $statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var \Psr\Http\Message\ResponseInterface $rawResponse
     */
    public \Psr\Http\Message\ResponseInterface $rawResponse;

    /**
     * Successful Response
     *
     * @var \Pago\Models\Components\AuthorizeResponseUser|\Pago\Models\Components\AuthorizeResponseOrganization|null $responseOauth2Authorize
     */
    public Components\AuthorizeResponseUser|Components\AuthorizeResponseOrganization|null $responseOauth2Authorize = null;

    /**
     * @param  string  $contentType
     * @param  int  $statusCode
     * @param  \Psr\Http\Message\ResponseInterface  $rawResponse
     * @param  \Pago\Models\Components\AuthorizeResponseUser|\Pago\Models\Components\AuthorizeResponseOrganization|null  $responseOauth2Authorize
     * @phpstan-pure
     */
    public function __construct(string $contentType, int $statusCode, \Psr\Http\Message\ResponseInterface $rawResponse, Components\AuthorizeResponseUser|Components\AuthorizeResponseOrganization|null $responseOauth2Authorize = null)
    {
        $this->contentType = $contentType;
        $this->statusCode = $statusCode;
        $this->rawResponse = $rawResponse;
        $this->responseOauth2Authorize = $responseOauth2Authorize;
    }
}