<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class OrdersUpdateRequest
{
    /**
     * The order ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Pago\Models\Components\OrderUpdate $orderUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\OrderUpdate $orderUpdate;

    /**
     * @param  string  $id
     * @param  \Pago\Models\Components\OrderUpdate  $orderUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\OrderUpdate $orderUpdate)
    {
        $this->id = $id;
        $this->orderUpdate = $orderUpdate;
    }
}