<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class OrganizationsUpdateRequest
{
    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Pago\Models\Components\OrganizationUpdate $organizationUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\OrganizationUpdate $organizationUpdate;

    /**
     * @param  string  $id
     * @param  \Pago\Models\Components\OrganizationUpdate  $organizationUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\OrganizationUpdate $organizationUpdate)
    {
        $this->id = $id;
        $this->organizationUpdate = $organizationUpdate;
    }
}