<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class OrganizationAccessTokensUpdateRequest
{
    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Pago\Models\Components\OrganizationAccessTokenUpdate $organizationAccessTokenUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\OrganizationAccessTokenUpdate $organizationAccessTokenUpdate;

    /**
     * @param  string  $id
     * @param  \Pago\Models\Components\OrganizationAccessTokenUpdate  $organizationAccessTokenUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\OrganizationAccessTokenUpdate $organizationAccessTokenUpdate)
    {
        $this->id = $id;
        $this->organizationAccessTokenUpdate = $organizationAccessTokenUpdate;
    }
}