<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class ProductsUpdateRequest
{
    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Pago\Models\Components\ProductUpdate $productUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\ProductUpdate $productUpdate;

    /**
     * @param  string  $id
     * @param  \Pago\Models\Components\ProductUpdate  $productUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\ProductUpdate $productUpdate)
    {
        $this->id = $id;
        $this->productUpdate = $productUpdate;
    }
}