<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Operations;

use Pago\Models\Components;
use Pago\Utils\SpeakeasyMetadata;
class SubscriptionsUpdateRequest
{
    /**
     * The subscription ID.
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var \Pago\Models\Components\SubscriptionUpdateProduct|\Pago\Models\Components\SubscriptionUpdateDiscount|\Pago\Models\Components\SubscriptionUpdateTrial|\Pago\Models\Components\SubscriptionUpdateSeats|\Pago\Models\Components\SubscriptionUpdateBillingPeriod|\Pago\Models\Components\SubscriptionCancel|\Pago\Models\Components\SubscriptionRevoke $subscriptionUpdate
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public Components\SubscriptionUpdateProduct|Components\SubscriptionUpdateDiscount|Components\SubscriptionUpdateTrial|Components\SubscriptionUpdateSeats|Components\SubscriptionUpdateBillingPeriod|Components\SubscriptionCancel|Components\SubscriptionRevoke $subscriptionUpdate;

    /**
     * @param  string  $id
     * @param  \Pago\Models\Components\SubscriptionUpdateProduct|\Pago\Models\Components\SubscriptionUpdateDiscount|\Pago\Models\Components\SubscriptionUpdateTrial|\Pago\Models\Components\SubscriptionUpdateSeats|\Pago\Models\Components\SubscriptionUpdateBillingPeriod|\Pago\Models\Components\SubscriptionCancel|\Pago\Models\Components\SubscriptionRevoke  $subscriptionUpdate
     * @phpstan-pure
     */
    public function __construct(string $id, Components\SubscriptionUpdateProduct|Components\SubscriptionUpdateDiscount|Components\SubscriptionUpdateTrial|Components\SubscriptionUpdateSeats|Components\SubscriptionUpdateBillingPeriod|Components\SubscriptionCancel|Components\SubscriptionRevoke $subscriptionUpdate)
    {
        $this->id = $id;
        $this->subscriptionUpdate = $subscriptionUpdate;
    }
}