<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


class AuthorizeResponseUser
{
    /**
     *
     * @var \Pago\Models\Components\OAuth2ClientPublic $client
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('client')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\OAuth2ClientPublic')]
    public OAuth2ClientPublic $client;

    /**
     * $scopes
     *
     * @var array<\Pago\Models\Components\Scope> $scopes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scopes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Pago\Models\Components\Scope>')]
    public array $scopes;

    /**
     *
     * @var ?\Pago\Models\Components\AuthorizeUser $sub
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sub')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\AuthorizeUser|null')]
    public ?AuthorizeUser $sub;

    /**
     * $scopeDisplayNames
     *
     * @var ?array<string, string> $scopeDisplayNames
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scope_display_names')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $scopeDisplayNames = null;

    /**
     *
     * @var string $subType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sub_type')]
    public string $subType;

    /**
     * @param  \Pago\Models\Components\OAuth2ClientPublic  $client
     * @param  string  $subType
     * @param  array<\Pago\Models\Components\Scope>  $scopes
     * @param  ?\Pago\Models\Components\AuthorizeUser  $sub
     * @param  ?array<string, string>  $scopeDisplayNames
     * @phpstan-pure
     */
    public function __construct(OAuth2ClientPublic $client, array $scopes, ?AuthorizeUser $sub = null, ?array $scopeDisplayNames = null, string $subType = 'user')
    {
        $this->client = $client;
        $this->scopes = $scopes;
        $this->sub = $sub;
        $this->scopeDisplayNames = $scopeDisplayNames;
        $this->subType = $subType;
    }
}