<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


class BenefitLicenseKeysProperties
{
    /**
     *
     * @var ?string $prefix
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('prefix')]
    public ?string $prefix;

    /**
     *
     * @var ?\Pago\Models\Components\BenefitLicenseKeyExpirationProperties $expires
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expires')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\BenefitLicenseKeyExpirationProperties|null')]
    public ?BenefitLicenseKeyExpirationProperties $expires;

    /**
     *
     * @var ?\Pago\Models\Components\BenefitLicenseKeyActivationProperties $activations
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('activations')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\BenefitLicenseKeyActivationProperties|null')]
    public ?BenefitLicenseKeyActivationProperties $activations;

    /**
     *
     * @var ?int $limitUsage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('limit_usage')]
    public ?int $limitUsage;

    /**
     * @param  ?string  $prefix
     * @param  ?\Pago\Models\Components\BenefitLicenseKeyExpirationProperties  $expires
     * @param  ?\Pago\Models\Components\BenefitLicenseKeyActivationProperties  $activations
     * @param  ?int  $limitUsage
     * @phpstan-pure
     */
    public function __construct(?string $prefix = null, ?BenefitLicenseKeyExpirationProperties $expires = null, ?BenefitLicenseKeyActivationProperties $activations = null, ?int $limitUsage = null)
    {
        $this->prefix = $prefix;
        $this->expires = $expires;
        $this->activations = $activations;
        $this->limitUsage = $limitUsage;
    }
}