<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


enum BillingAddressFieldMode: string
{
    case Required = 'required';
    case Optional = 'optional';
    case Disabled = 'disabled';
}
