<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


/** CustomerOrganizationData - Schema of an organization and related data for customer portal. */
class CustomerOrganizationData
{
    /**
     *
     * @var \Pago\Models\Components\CustomerOrganization $organization
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\CustomerOrganization')]
    public CustomerOrganization $organization;

    /**
     * $products
     *
     * @var array<\Pago\Models\Components\CustomerProduct> $products
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('products')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Pago\Models\Components\CustomerProduct>')]
    public array $products;

    /**
     * @param  \Pago\Models\Components\CustomerOrganization  $organization
     * @param  array<\Pago\Models\Components\CustomerProduct>  $products
     * @phpstan-pure
     */
    public function __construct(CustomerOrganization $organization, array $products)
    {
        $this->organization = $organization;
        $this->products = $products;
    }
}