<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


/** CustomerStateBenefitGrant - An active benefit grant for a customer. */
class CustomerStateBenefitGrant
{
    /**
     * The ID of the grant.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Creation timestamp of the object.
     *
     * @var \DateTime $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public \DateTime $createdAt;

    /**
     * The timestamp when the benefit was granted.
     *
     * @var \DateTime $grantedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('granted_at')]
    public \DateTime $grantedAt;

    /**
     * The ID of the benefit concerned by this grant.
     *
     * @var string $benefitId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('benefit_id')]
    public string $benefitId;

    /**
     *
     * @var \Pago\Models\Components\BenefitType $benefitType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('benefit_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\BenefitType')]
    public BenefitType $benefitType;

    /**
     * $benefitMetadata
     *
     * @var array<string, string|int|float|bool> $benefitMetadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('benefit_metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, string|int|float|bool>')]
    public array $benefitMetadata;

    /**
     *
     * @var \Pago\Models\Components\BenefitGrantDiscordProperties|\Pago\Models\Components\BenefitGrantGitHubRepositoryProperties|\Pago\Models\Components\BenefitGrantDownloadablesProperties|\Pago\Models\Components\BenefitGrantLicenseKeysProperties|\Pago\Models\Components\BenefitGrantCustomProperties|\Pago\Models\Components\BenefitGrantFeatureFlagProperties $properties
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('properties')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\BenefitGrantDiscordProperties|\Pago\Models\Components\BenefitGrantGitHubRepositoryProperties|\Pago\Models\Components\BenefitGrantDownloadablesProperties|\Pago\Models\Components\BenefitGrantLicenseKeysProperties|\Pago\Models\Components\BenefitGrantCustomProperties|\Pago\Models\Components\BenefitGrantFeatureFlagProperties')]
    public BenefitGrantDiscordProperties|BenefitGrantGitHubRepositoryProperties|BenefitGrantDownloadablesProperties|BenefitGrantLicenseKeysProperties|BenefitGrantCustomProperties|BenefitGrantFeatureFlagProperties $properties;

    /**
     * Last modification timestamp of the object.
     *
     * @var ?\DateTime $modifiedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('modified_at')]
    public ?\DateTime $modifiedAt;

    /**
     * @param  string  $id
     * @param  \DateTime  $createdAt
     * @param  \DateTime  $grantedAt
     * @param  string  $benefitId
     * @param  \Pago\Models\Components\BenefitType  $benefitType
     * @param  array<string, string|int|float|bool>  $benefitMetadata
     * @param  \Pago\Models\Components\BenefitGrantDiscordProperties|\Pago\Models\Components\BenefitGrantGitHubRepositoryProperties|\Pago\Models\Components\BenefitGrantDownloadablesProperties|\Pago\Models\Components\BenefitGrantLicenseKeysProperties|\Pago\Models\Components\BenefitGrantCustomProperties|\Pago\Models\Components\BenefitGrantFeatureFlagProperties  $properties
     * @param  ?\DateTime  $modifiedAt
     * @phpstan-pure
     */
    public function __construct(string $id, \DateTime $createdAt, \DateTime $grantedAt, string $benefitId, BenefitType $benefitType, array $benefitMetadata, BenefitGrantDiscordProperties|BenefitGrantGitHubRepositoryProperties|BenefitGrantDownloadablesProperties|BenefitGrantLicenseKeysProperties|BenefitGrantCustomProperties|BenefitGrantFeatureFlagProperties $properties, ?\DateTime $modifiedAt = null)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->grantedAt = $grantedAt;
        $this->benefitId = $benefitId;
        $this->benefitType = $benefitType;
        $this->benefitMetadata = $benefitMetadata;
        $this->properties = $properties;
        $this->modifiedAt = $modifiedAt;
    }
}