<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


class CustomerPaymentMethodCreateSucceededResponse
{
    /**
     *
     * @var \Pago\Models\Components\PaymentMethodCard|\Pago\Models\Components\PaymentMethodGeneric $paymentMethod
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('payment_method')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\PaymentMethodCard|\Pago\Models\Components\PaymentMethodGeneric')]
    public PaymentMethodCard|PaymentMethodGeneric $paymentMethod;

    /**
     *
     * @var string $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    public string $status;

    /**
     * @param  string  $status
     * @param  \Pago\Models\Components\PaymentMethodCard|\Pago\Models\Components\PaymentMethodGeneric  $paymentMethod
     * @phpstan-pure
     */
    public function __construct(PaymentMethodCard|PaymentMethodGeneric $paymentMethod, string $status = 'succeeded')
    {
        $this->paymentMethod = $paymentMethod;
        $this->status = $status;
    }
}