<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


/** CustomerOrderUpdate - Schema to update an order. */
class CustomerOrderUpdate
{
    /**
     * The name of the customer that should appear on the invoice.
     *
     * @var ?string $billingName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $billingName = null;

    /**
     * The address of the customer that should appear on the invoice. Country and state fields cannot be updated.
     *
     * @var ?\Pago\Models\Components\AddressInput $billingAddress
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billing_address')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\AddressInput|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?AddressInput $billingAddress = null;

    /**
     * @param  ?string  $billingName
     * @param  ?\Pago\Models\Components\AddressInput  $billingAddress
     * @phpstan-pure
     */
    public function __construct(?string $billingName = null, ?AddressInput $billingAddress = null)
    {
        $this->billingName = $billingName;
        $this->billingAddress = $billingAddress;
    }
}