<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


/** CustomerPortalMemberUpdate - Schema for updating a member's role in the customer portal. */
class CustomerPortalMemberUpdate
{
    /**
     * The new role for the member.
     *
     * @var ?\Pago\Models\Components\MemberRole $role
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\MemberRole|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?MemberRole $role = null;

    /**
     * @param  ?\Pago\Models\Components\MemberRole  $role
     * @phpstan-pure
     */
    public function __construct(?MemberRole $role = null)
    {
        $this->role = $role;
    }
}