<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


class CustomerBenefitGrantDiscordUpdate
{
    /**
     *
     * @var \Pago\Models\Components\CustomerBenefitGrantDiscordPropertiesUpdate $properties
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('properties')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\CustomerBenefitGrantDiscordPropertiesUpdate')]
    public CustomerBenefitGrantDiscordPropertiesUpdate $properties;

    /**
     *
     * @var string $benefitType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('benefit_type')]
    public string $benefitType;

    /**
     * @param  string  $benefitType
     * @param  \Pago\Models\Components\CustomerBenefitGrantDiscordPropertiesUpdate  $properties
     * @phpstan-pure
     */
    public function __construct(CustomerBenefitGrantDiscordPropertiesUpdate $properties, string $benefitType = 'discord')
    {
        $this->properties = $properties;
        $this->benefitType = $benefitType;
    }
}