<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


enum DiscountType: string
{
    case Fixed = 'fixed';
    case Percentage = 'percentage';
}
