<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


class DownloadableRead
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $benefitId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('benefit_id')]
    public string $benefitId;

    /**
     *
     * @var \Pago\Models\Components\FileDownload $file
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('file')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\FileDownload')]
    public FileDownload $file;

    /**
     * @param  string  $id
     * @param  string  $benefitId
     * @param  \Pago\Models\Components\FileDownload  $file
     * @phpstan-pure
     */
    public function __construct(string $id, string $benefitId, FileDownload $file)
    {
        $this->id = $id;
        $this->benefitId = $benefitId;
        $this->file = $file;
    }
}