<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


class EventsIngest
{
    /**
     * List of events to ingest.
     *
     * @var array<\Pago\Models\Components\EventCreateCustomer|\Pago\Models\Components\EventCreateExternalCustomer> $events
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('events')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Pago\Models\Components\EventCreateCustomer|\Pago\Models\Components\EventCreateExternalCustomer>')]
    public array $events;

    /**
     * @param  array<\Pago\Models\Components\EventCreateCustomer|\Pago\Models\Components\EventCreateExternalCustomer>  $events
     * @phpstan-pure
     */
    public function __construct(array $events)
    {
        $this->events = $events;
    }
}