<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


class Filter
{
    /**
     *
     * @var \Pago\Models\Components\FilterConjunction $conjunction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('conjunction')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\FilterConjunction')]
    public FilterConjunction $conjunction;

    /**
     * $clauses
     *
     * @var array<\Pago\Models\Components\FilterClause|\Pago\Models\Components\Filter> $clauses
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clauses')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Pago\Models\Components\FilterClause|\Pago\Models\Components\Filter>')]
    public array $clauses;

    /**
     * @param  \Pago\Models\Components\FilterConjunction  $conjunction
     * @param  array<\Pago\Models\Components\FilterClause|\Pago\Models\Components\Filter>  $clauses
     * @phpstan-pure
     */
    public function __construct(FilterConjunction $conjunction, array $clauses)
    {
        $this->conjunction = $conjunction;
        $this->clauses = $clauses;
    }
}