<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


enum LicenseKeyStatus: string
{
    case Granted = 'granted';
    case Revoked = 'revoked';
    case Disabled = 'disabled';
}
