<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


class ListResourceEvent
{
    /**
     * $items
     *
     * @var array<\Pago\Models\Components\MeterCreditEvent|\Pago\Models\Components\MeterResetEvent|\Pago\Models\Components\BenefitGrantedEvent|\Pago\Models\Components\BenefitCycledEvent|\Pago\Models\Components\BenefitUpdatedEvent|\Pago\Models\Components\BenefitRevokedEvent|\Pago\Models\Components\SubscriptionCreatedEvent|\Pago\Models\Components\SubscriptionUpdatedEvent|\Pago\Models\Components\SubscriptionCycledEvent|\Pago\Models\Components\SubscriptionCanceledEvent|\Pago\Models\Components\SubscriptionRevokedEvent|\Pago\Models\Components\SubscriptionUncanceledEvent|\Pago\Models\Components\SubscriptionProductUpdatedEvent|\Pago\Models\Components\SubscriptionSeatsUpdatedEvent|\Pago\Models\Components\SubscriptionBillingPeriodUpdatedEvent|\Pago\Models\Components\OrderPaidEvent|\Pago\Models\Components\OrderRefundedEvent|\Pago\Models\Components\OrderVoidedEvent|\Pago\Models\Components\CheckoutCreatedEvent|\Pago\Models\Components\CustomerCreatedEvent|\Pago\Models\Components\CustomerUpdatedEvent|\Pago\Models\Components\CustomerDeletedEvent|\Pago\Models\Components\BalanceOrderEvent|\Pago\Models\Components\BalanceCreditOrderEvent|\Pago\Models\Components\BalanceRefundEvent|\Pago\Models\Components\BalanceRefundReversalEvent|\Pago\Models\Components\BalanceDisputeEvent|\Pago\Models\Components\BalanceDisputeReversalEvent|\Pago\Models\Components\UserEvent> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Pago\Models\Components\MeterCreditEvent|\Pago\Models\Components\MeterResetEvent|\Pago\Models\Components\BenefitGrantedEvent|\Pago\Models\Components\BenefitCycledEvent|\Pago\Models\Components\BenefitUpdatedEvent|\Pago\Models\Components\BenefitRevokedEvent|\Pago\Models\Components\SubscriptionCreatedEvent|\Pago\Models\Components\SubscriptionUpdatedEvent|\Pago\Models\Components\SubscriptionCycledEvent|\Pago\Models\Components\SubscriptionCanceledEvent|\Pago\Models\Components\SubscriptionRevokedEvent|\Pago\Models\Components\SubscriptionUncanceledEvent|\Pago\Models\Components\SubscriptionProductUpdatedEvent|\Pago\Models\Components\SubscriptionSeatsUpdatedEvent|\Pago\Models\Components\SubscriptionBillingPeriodUpdatedEvent|\Pago\Models\Components\OrderPaidEvent|\Pago\Models\Components\OrderRefundedEvent|\Pago\Models\Components\OrderVoidedEvent|\Pago\Models\Components\CheckoutCreatedEvent|\Pago\Models\Components\CustomerCreatedEvent|\Pago\Models\Components\CustomerUpdatedEvent|\Pago\Models\Components\CustomerDeletedEvent|\Pago\Models\Components\BalanceOrderEvent|\Pago\Models\Components\BalanceCreditOrderEvent|\Pago\Models\Components\BalanceRefundEvent|\Pago\Models\Components\BalanceRefundReversalEvent|\Pago\Models\Components\BalanceDisputeEvent|\Pago\Models\Components\BalanceDisputeReversalEvent|\Pago\Models\Components\UserEvent>')]
    public array $items;

    /**
     *
     * @var \Pago\Models\Components\Pagination $pagination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pagination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\Pagination')]
    public Pagination $pagination;

    /**
     * @param  array<\Pago\Models\Components\MeterCreditEvent|\Pago\Models\Components\MeterResetEvent|\Pago\Models\Components\BenefitGrantedEvent|\Pago\Models\Components\BenefitCycledEvent|\Pago\Models\Components\BenefitUpdatedEvent|\Pago\Models\Components\BenefitRevokedEvent|\Pago\Models\Components\SubscriptionCreatedEvent|\Pago\Models\Components\SubscriptionUpdatedEvent|\Pago\Models\Components\SubscriptionCycledEvent|\Pago\Models\Components\SubscriptionCanceledEvent|\Pago\Models\Components\SubscriptionRevokedEvent|\Pago\Models\Components\SubscriptionUncanceledEvent|\Pago\Models\Components\SubscriptionProductUpdatedEvent|\Pago\Models\Components\SubscriptionSeatsUpdatedEvent|\Pago\Models\Components\SubscriptionBillingPeriodUpdatedEvent|\Pago\Models\Components\OrderPaidEvent|\Pago\Models\Components\OrderRefundedEvent|\Pago\Models\Components\OrderVoidedEvent|\Pago\Models\Components\CheckoutCreatedEvent|\Pago\Models\Components\CustomerCreatedEvent|\Pago\Models\Components\CustomerUpdatedEvent|\Pago\Models\Components\CustomerDeletedEvent|\Pago\Models\Components\BalanceOrderEvent|\Pago\Models\Components\BalanceCreditOrderEvent|\Pago\Models\Components\BalanceRefundEvent|\Pago\Models\Components\BalanceRefundReversalEvent|\Pago\Models\Components\BalanceDisputeEvent|\Pago\Models\Components\BalanceDisputeReversalEvent|\Pago\Models\Components\UserEvent>  $items
     * @param  \Pago\Models\Components\Pagination  $pagination
     * @phpstan-pure
     */
    public function __construct(array $items, Pagination $pagination)
    {
        $this->items = $items;
        $this->pagination = $pagination;
    }
}