<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


class ListResourceWebhookDelivery
{
    /**
     * $items
     *
     * @var array<\Pago\Models\Components\WebhookDelivery> $items
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('items')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Pago\Models\Components\WebhookDelivery>')]
    public array $items;

    /**
     *
     * @var \Pago\Models\Components\Pagination $pagination
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pagination')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\Pagination')]
    public Pagination $pagination;

    /**
     * @param  array<\Pago\Models\Components\WebhookDelivery>  $items
     * @param  \Pago\Models\Components\Pagination  $pagination
     * @phpstan-pure
     */
    public function __construct(array $items, Pagination $pagination)
    {
        $this->items = $items;
        $this->pagination = $pagination;
    }
}