<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


/** MetricsResponse - Metrics response schema. */
class MetricsResponse
{
    /**
     * List of data for each timestamp.
     *
     * @var array<\Pago\Models\Components\MetricPeriod> $periods
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('periods')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Pago\Models\Components\MetricPeriod>')]
    public array $periods;

    /**
     *
     * @var \Pago\Models\Components\MetricsTotals $totals
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totals')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\MetricsTotals')]
    public MetricsTotals $totals;

    /**
     *
     * @var \Pago\Models\Components\Metrics $metrics
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metrics')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\Metrics')]
    public Metrics $metrics;

    /**
     * @param  array<\Pago\Models\Components\MetricPeriod>  $periods
     * @param  \Pago\Models\Components\MetricsTotals  $totals
     * @param  \Pago\Models\Components\Metrics  $metrics
     * @phpstan-pure
     */
    public function __construct(array $periods, MetricsTotals $totals, Metrics $metrics)
    {
        $this->periods = $periods;
        $this->totals = $totals;
        $this->metrics = $metrics;
    }
}