<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


class OrganizationSocialLink
{
    /**
     *
     * @var \Pago\Models\Components\OrganizationSocialPlatforms $platform
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('platform')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\OrganizationSocialPlatforms')]
    public OrganizationSocialPlatforms $platform;

    /**
     * The URL to the organization profile
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * @param  \Pago\Models\Components\OrganizationSocialPlatforms  $platform
     * @param  string  $url
     * @phpstan-pure
     */
    public function __construct(OrganizationSocialPlatforms $platform, string $url)
    {
        $this->platform = $platform;
        $this->url = $url;
    }
}