<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


class OrganizationCustomerPortalSettings
{
    /**
     *
     * @var \Pago\Models\Components\CustomerPortalUsageSettings $usage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('usage')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\CustomerPortalUsageSettings')]
    public CustomerPortalUsageSettings $usage;

    /**
     *
     * @var \Pago\Models\Components\CustomerPortalSubscriptionSettings $subscription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subscription')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\CustomerPortalSubscriptionSettings')]
    public CustomerPortalSubscriptionSettings $subscription;

    /**
     * @param  \Pago\Models\Components\CustomerPortalUsageSettings  $usage
     * @param  \Pago\Models\Components\CustomerPortalSubscriptionSettings  $subscription
     * @phpstan-pure
     */
    public function __construct(CustomerPortalUsageSettings $usage, CustomerPortalSubscriptionSettings $subscription)
    {
        $this->usage = $usage;
        $this->subscription = $subscription;
    }
}