<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


class OrganizationAccessTokenCreateResponse
{
    /**
     *
     * @var \Pago\Models\Components\OrganizationAccessToken $organizationAccessToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('organization_access_token')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\OrganizationAccessToken')]
    public OrganizationAccessToken $organizationAccessToken;

    /**
     *
     * @var string $token
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('token')]
    public string $token;

    /**
     * @param  \Pago\Models\Components\OrganizationAccessToken  $organizationAccessToken
     * @param  string  $token
     * @phpstan-pure
     */
    public function __construct(OrganizationAccessToken $organizationAccessToken, string $token)
    {
        $this->organizationAccessToken = $organizationAccessToken;
        $this->token = $token;
    }
}