<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


class OrganizationAccessTokenUpdate
{
    /**
     *
     * @var ?string $comment
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('comment')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $comment = null;

    /**
     * $scopes
     *
     * @var ?array<\Pago\Models\Components\AvailableScope> $scopes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scopes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Pago\Models\Components\AvailableScope>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $scopes = null;

    /**
     * @param  ?string  $comment
     * @param  ?array<\Pago\Models\Components\AvailableScope>  $scopes
     * @phpstan-pure
     */
    public function __construct(?string $comment = null, ?array $scopes = null)
    {
        $this->comment = $comment;
        $this->scopes = $scopes;
    }
}