<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


enum Status: string
{
    case Active = 'active';
    case Trialing = 'trialing';
}
