<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


/**
 * WebhookSubscriptionCanceledPayload - Sent when a subscription is canceled.
 *
 * Customers might still have access until the end of the current period.
 *
 * **Discord & Slack support:** Full
 */
class WebhookSubscriptionCanceledPayload
{
    /**
     *
     * @var \DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     *
     * @var \Pago\Models\Components\Subscription $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\Subscription')]
    public Subscription $data;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * @param  string  $type
     * @param  \DateTime  $timestamp
     * @param  \Pago\Models\Components\Subscription  $data
     * @phpstan-pure
     */
    public function __construct(\DateTime $timestamp, Subscription $data, string $type = 'subscription.canceled')
    {
        $this->timestamp = $timestamp;
        $this->data = $data;
        $this->type = $type;
    }
}