<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


/**
 * WebhookCustomerStateChangedPayload - Sent when a customer state has changed.
 *
 *
 * It's triggered when:
 *
 * * Customer is created, updated or deleted.
 * * A subscription is created or updated.
 * * A benefit is granted or revoked.
 *
 * **Discord & Slack support:** Basic
 */
class WebhookCustomerStateChangedPayload
{
    /**
     *
     * @var \DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     *
     * @var \Pago\Models\Components\CustomerStateIndividual|\Pago\Models\Components\CustomerStateTeam $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\CustomerStateIndividual|\Pago\Models\Components\CustomerStateTeam')]
    #[\Speakeasy\Serializer\Annotation\UnionDiscriminator(field: 'type', map: ['individual' => '\Pago\Models\Components\CustomerStateIndividual', 'team' => '\Pago\Models\Components\CustomerStateTeam'])]
    public CustomerStateIndividual|CustomerStateTeam $data;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * @param  string  $type
     * @param  \DateTime  $timestamp
     * @param  \Pago\Models\Components\CustomerStateIndividual|\Pago\Models\Components\CustomerStateTeam  $data
     * @phpstan-pure
     */
    public function __construct(\DateTime $timestamp, CustomerStateIndividual|CustomerStateTeam $data, string $type = 'customer.state_changed')
    {
        $this->timestamp = $timestamp;
        $this->data = $data;
        $this->type = $type;
    }
}