<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


/**
 * WebhookBenefitGrantUpdatedPayload - Sent when a benefit grant is updated.
 *
 *
 * **Discord & Slack support:** Basic
 */
class WebhookBenefitGrantUpdatedPayload
{
    /**
     *
     * @var \DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     *
     * @var \Pago\Models\Components\BenefitGrantDiscordWebhook|\Pago\Models\Components\BenefitGrantCustomWebhook|\Pago\Models\Components\BenefitGrantGitHubRepositoryWebhook|\Pago\Models\Components\BenefitGrantDownloadablesWebhook|\Pago\Models\Components\BenefitGrantLicenseKeysWebhook|\Pago\Models\Components\BenefitGrantMeterCreditWebhook|\Pago\Models\Components\BenefitGrantFeatureFlagWebhook $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\BenefitGrantDiscordWebhook|\Pago\Models\Components\BenefitGrantCustomWebhook|\Pago\Models\Components\BenefitGrantGitHubRepositoryWebhook|\Pago\Models\Components\BenefitGrantDownloadablesWebhook|\Pago\Models\Components\BenefitGrantLicenseKeysWebhook|\Pago\Models\Components\BenefitGrantMeterCreditWebhook|\Pago\Models\Components\BenefitGrantFeatureFlagWebhook')]
    public BenefitGrantDiscordWebhook|BenefitGrantCustomWebhook|BenefitGrantGitHubRepositoryWebhook|BenefitGrantDownloadablesWebhook|BenefitGrantLicenseKeysWebhook|BenefitGrantMeterCreditWebhook|BenefitGrantFeatureFlagWebhook $data;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * @param  string  $type
     * @param  \DateTime  $timestamp
     * @param  \Pago\Models\Components\BenefitGrantDiscordWebhook|\Pago\Models\Components\BenefitGrantCustomWebhook|\Pago\Models\Components\BenefitGrantGitHubRepositoryWebhook|\Pago\Models\Components\BenefitGrantDownloadablesWebhook|\Pago\Models\Components\BenefitGrantLicenseKeysWebhook|\Pago\Models\Components\BenefitGrantMeterCreditWebhook|\Pago\Models\Components\BenefitGrantFeatureFlagWebhook  $data
     * @phpstan-pure
     */
    public function __construct(\DateTime $timestamp, BenefitGrantDiscordWebhook|BenefitGrantCustomWebhook|BenefitGrantGitHubRepositoryWebhook|BenefitGrantDownloadablesWebhook|BenefitGrantLicenseKeysWebhook|BenefitGrantMeterCreditWebhook|BenefitGrantFeatureFlagWebhook $data, string $type = 'benefit_grant.updated')
    {
        $this->timestamp = $timestamp;
        $this->data = $data;
        $this->type = $type;
    }
}