<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago\Models\Components;


/**
 * WebhookCustomerDeletedPayload - Sent when a customer is deleted.
 *
 *
 * **Discord & Slack support:** Basic
 */
class WebhookCustomerDeletedPayload
{
    /**
     *
     * @var \DateTime $timestamp
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timestamp')]
    public \DateTime $timestamp;

    /**
     *
     * @var \Pago\Models\Components\CustomerIndividual|\Pago\Models\Components\CustomerTeam $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Pago\Models\Components\CustomerIndividual|\Pago\Models\Components\CustomerTeam')]
    #[\Speakeasy\Serializer\Annotation\UnionDiscriminator(field: 'type', map: ['individual' => '\Pago\Models\Components\CustomerIndividual', 'team' => '\Pago\Models\Components\CustomerTeam'])]
    public CustomerIndividual|CustomerTeam $data;

    /**
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * @param  string  $type
     * @param  \DateTime  $timestamp
     * @param  \Pago\Models\Components\CustomerIndividual|\Pago\Models\Components\CustomerTeam  $data
     * @phpstan-pure
     */
    public function __construct(\DateTime $timestamp, CustomerIndividual|CustomerTeam $data, string $type = 'customer.deleted')
    {
        $this->timestamp = $timestamp;
        $this->data = $data;
        $this->type = $type;
    }
}