<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Pago;



class CustomerPortal
{
    private SDKConfiguration $sdkConfiguration;
    public PagoBenefitGrants $benefitGrants;

    public PagoCustomers $customers;

    public PagoCustomerMeters $customerMeters;

    public Seats $seats;

    public CustomerSession $customerSession;

    public Downloadables $downloadables;

    public PagoLicenseKeys $licenseKeys;

    public PagoMembers $members;

    public PagoOrders $orders;

    public PagoOrganizations $organizations;

    public PagoSubscriptions $subscriptions;

    public Wallets $wallets;

    /**
     * @param  SDKConfiguration  $sdkConfig
     */
    public function __construct(public SDKConfiguration $sdkConfig)
    {
        $this->sdkConfiguration = $sdkConfig;
        $this->benefitGrants = new PagoBenefitGrants($this->sdkConfiguration);
        $this->customers = new PagoCustomers($this->sdkConfiguration);
        $this->customerMeters = new PagoCustomerMeters($this->sdkConfiguration);
        $this->seats = new Seats($this->sdkConfiguration);
        $this->customerSession = new CustomerSession($this->sdkConfiguration);
        $this->downloadables = new Downloadables($this->sdkConfiguration);
        $this->licenseKeys = new PagoLicenseKeys($this->sdkConfiguration);
        $this->members = new PagoMembers($this->sdkConfiguration);
        $this->orders = new PagoOrders($this->sdkConfiguration);
        $this->organizations = new PagoOrganizations($this->sdkConfiguration);
        $this->subscriptions = new PagoSubscriptions($this->sdkConfiguration);
        $this->wallets = new Wallets($this->sdkConfiguration);
    }
    /**
     * @param  string  $baseUrl
     * @param  array<string, string>  $urlVariables
     *
     * @return string
     */
    public function getUrl(string $baseUrl, array $urlVariables): string
    {
        $serverDetails = $this->sdkConfiguration->getServerDetails();

        if ($baseUrl == null) {
            $baseUrl = $serverDetails->baseUrl;
        }

        if ($urlVariables == null) {
            $urlVariables = $serverDetails->options;
        }

        return Utils\Utils::templateUrl($baseUrl, $urlVariables);
    }

}